### ISSUE TITLE
Rest API installed?

### ISSUE THREAD

**Issue by mornindew** [andrea-patricelli/syncope-docker#8]
Hi, 
First of all, thank you very much for this repository!  Not sure where I should put this but I am hoping you can help me.  I was able to get your docker images up and running.  Everything worked pretty well.  I updated the version numbers but kept most of the DockerFile the same.  I am running off of Branch 2_0_X.  

I then created Kubernetes deployments (created stateful sets and my replica sets) and services for everything and got it running.   A few hiccups later it seems to be working fine.  The only exception is that the swagger or rest API does't appear to be deployed.

I tried to hit the core container "http://IP_OF_CORE:PORT/syncope/rest/" and it comes back 404.   Is there something that I need to do to enable the rest API (and swagger docs) when installing from the deb?

Thank you very much in advance.

Craig

**Comment by andrea-patricelli** [comment]
Hi!

thank you very much for your insterest. I'm glad that someone is interested in this  project!
Unfortunately merely upgrading Syncope versions in Dockerfiles is not enough, since between Syncope releases could be some structural changes (database model or some properties) it needs to upgrade also Dockerfiles in order to fit with this developments.
I think that the best way is to follow steps from [1] to [4] in order to get the latest version. Or simply try to work with the current one, 2.0.2.

It's amazing to hear about Kubernetes and Syncope in replica with Kubernetes! I'm not skilled on it and would be glad, if you agree (obviously :), if you would like to contribute to this project; with a fork or simply submitting pull requests.

About your problems, I suggest to split it in two issues: upgrade + Syncope working in replica.

Unfortunately I'm the only maintainer of this repo and I'm too busy at the moment to contribute, but I'll schedule ASAP the upgrade to 2.0.6 or 2.0.7 (if available), so I can deal with it.

If you want also to contribute to Syncope project or simply let the community know about your work you can subscribe and write to Syncope users mailing list: user@syncope.apache.org
or dev mailing list: dev@syncope.apache.org
It's free ;)

Best regards,
Andrea

[1] https://cwiki.apache.org/confluence/display/SYNCOPE/Upgrade+from+2.0.2+to+2.0.3
[2] https://cwiki.apache.org/confluence/display/SYNCOPE/Upgrade+from+2.0.3+to+2.0.4
[3] https://cwiki.apache.org/confluence/display/SYNCOPE/Upgrade+from+2.0.4+to+2.0.5
[4] https://cwiki.apache.org/confluence/display/SYNCOPE/Upgrade+from+2.0.5+to+2.0.6

**Comment by mornindew** [comment]
Thank you very much.  I will give that a shot and see if I can get it working.   Once I do then I will be happy to commit back to the repository.   I am currently using my own private registry but see no reason why I cannot commit a generic version back into a public repository.   

I will try to keep you posted.

**Comment by andrea-patricelli** [comment]
Going to close this issue as side effect of pull request.
