### ISSUE TITLE
Working on Kubernetes

### ISSUE THREAD

**Issue by mornindew** [andrea-patricelli/syncope-docker#9]
Hi Andrea,

I finally got around to creating a base K8s installation of 2.0.6.   I started with your DockerFile and wouldn't mind adding it to this repository.   It is a pretty straightforward installation and I documented it.  It looks like you need to grant me access to merge my PR.   I created it on another branch and would merge and let you take a look at it.

Thanks again.

Craig

**Comment by andrea-patricelli** [comment]
Wow, awesome!
I've sent you a invitation. Let me kno if it is ok to make PR and/or push directly.

Have a nice day,
Andrea

**Comment by andrea-patricelli** [comment]
Ok thanks a lot!
Let me some days to study a bit kubernetes and to have syncope working. All info that I need arre in the install.adoc file right?

**Comment by mornindew** [comment]
Yup, should be.  I also included a link to an article that I helped to write a couple months ago.  It walks through the steps of setting up minikube.  Probably only need part 1 but the rest is still a lot of fun :)

https://www.linux.com/blog/learn/chapter/Intro-to-Kubernetes/2017/5/set-cicd-pipeline-kubernetes-part-1-overview

**Comment by andrea-patricelli** [comment]
Hi @mornindew !
And merry Christmas :)
I merged you'll pull request, tough I was not able to fully check the installation due to my Laptop that mounts only 8 GB of RAM.
But this is my problem, I'll solve it in a way or the other.
It would be great if you add some documentation also in the wiki, if you want, and advice about your developments also in the apache syncope dev community ;)

Moreover I upgraded  sources to 2.0.7 (released few days ago): Dockerfiles and docker-compose. I'll take care ASAP to realign also master branch.
